import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Providers from "./providers";
import LanguageProvider from "./i18nProvider";
import "./globals.css";
import Header from "@/components/header/header";
import Navbar from "@/components/navbar/navbar";
import SaleSummary from "@/components/features/sale/saleSummary/saleSummary";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          color: "var(--colorText)",
        }}
      >
        <LanguageProvider>
          <Providers>
            <div className="">
              <Navbar />
              <div className="flex flex-col flex-1">
                <Header />
                <div className="flex flex-1">
                  <div className="flex-1 overflow-y-auto ml-64">{children}</div>
                  <div className="fixed top-20 right-4 h-screen z-30">
                    <SaleSummary />
                  </div>
                </div>
              </div>
            </div>
          </Providers>
        </LanguageProvider>
      </body>
    </html>
  );
}
